name: Fetch Weather Data and Upload to Google Drive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6AM UTC

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.WEATHER_API_KEY }}
      GDRIVE_CREDS_JSON: ${{ secrets.GDRIVE_CREDS_JSON }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: python main.py
